### ISSUE TITLE
Chapter 4 - Technical Feedback

### ISSUE THREAD

**Issue by natec425** [jiddyy/head-first-java-cliffsnotes-example#1]
Peer Reviewers: @devinbooker616, @Patton-Burge

---

You have a couple of typos and misspellings.

- [x] @devinbooker616
- [x] @Patton-Burge

---
 You didn't note or demonstrate getters or setters.

- [x] @devinbooker616
- [x] @Patton-Burge

---

 You didn't note or demonstrate encapsulation.

- [x] @devinbooker616
- [x] @Patton-Burge

---

 You didn't note or demonstrate using reference types in an array.

- [x] @devinbooker616
- [x] @Patton-Burge

---

 You didn't note pass-by-value.

- [x] @devinbooker616
- [x] @Patton-Burge

**Comment by jiddyy** [comment]
Done with issues
